In [41]:
import cv2
import os
import numpy as np

In [42]:
im=cv2.imread('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/1/1 (1).jpg')

In [43]:
im2=cv2.resize(im,(8,32))

In [44]:
im3=cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)

In [45]:
im4=im3.flatten()

In [46]:
im4.shape

(256,)

In [47]:
im5=im4.reshape(32,8)
print(im5)

[[ 98  94  90 103 102  99  95  92]
 [210 205 194 191 184 183 181 179]
 [216 216 209 204 205 205 203 203]
 [210 206 208 204 202 201 199 199]
 [166 125 162 203 211 209 206 204]
 [115  30  80 178 213 209 204 202]
 [ 72   3  10 125 215 216 199 207]
 [ 46   1   1  62 187 221 203 214]
 [ 24   2  11  24 130 214 221 217]
 [  8   4  16   4  81 200 226 209]
 [ 44   4  11   3  39 170 228 219]
 [107  22   2   2  12 128 221 224]
 [184  75   7   2   3  83 199 223]
 [229 142  29   1   3  48 174 226]
 [234 196  66   6   5  24 149 230]
 [237 227 114  16   1  13 113 236]
 [236 250 179  44   2  11  57 219]
 [235 252 207  66   2   1  38 203]
 [237 248 231 105  12   2  23 181]
 [231 240 244 144  25   6   9 152]
 [236 247 245 166  34   3   5 132]
 [237 246 241 183  46   0   2 116]
 [236 244 248 209  67   3   1 100]
 [238 245 249 218  71   2   2  72]
 [239 241 248 227  89   1   6  58]
 [243 244 252 240 118   3   1  43]
 [237 241 246 244 143  10   1  39]
 [223 226 228 243 184  84  61  79]
 [239 241 240 250 24

In [48]:
cv2.imshow('ax', im3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [49]:
files=os.listdir('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/1')

In [50]:
x=np.empty((0,256))
y=np.array([])
for filename in files:
    im=cv2.imread('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/1/'+filename)
    im2=cv2.resize(im,(8,32))
    im3=cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4=im3.flatten()
    x=np.append(x,[im4],axis=0)
    y=np.append(y,1)

In [51]:
files=os.listdir('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/2')
for filename in files:
    im=cv2.imread('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/2/'+filename)
    im2=cv2.resize(im,(8,32))
    im3=cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4=im3.flatten()
    x=np.append(x,[im4],axis=0)
    y=np.append(y,2)

In [52]:
files=os.listdir('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/3')
for filename in files:
    im=cv2.imread('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/3/'+filename)
    im2=cv2.resize(im,(8,32))
    im3=cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4=im3.flatten()
    x=np.append(x,[im4],axis=0)
    y=np.append(y,3)

In [56]:
files=os.listdir('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/4')
for filename in files:
    im=cv2.imread('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/4/'+filename)
    im2=cv2.resize(im,(8,32))
    im3=cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4=im3.flatten()
    x=np.append(x,[im4],axis=0)
    y=np.append(y,4)

In [67]:
files=os.listdir('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/5')
for filename in files:
    im=cv2.imread('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/5/'+filename)
    im2=cv2.resize(im,(8,32))
    im3=cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4=im3.flatten()
    x=np.append(x,[im4],axis=0)
    y=np.append(y,5)

In [77]:
files=os.listdir('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/6')
for filename in files:
    im=cv2.imread('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/6/'+filename)
    im2=cv2.resize(im,(8,32))
    im3=cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4=im3.flatten()
    x=np.append(x,[im4],axis=0)
    y=np.append(y,6)

In [86]:
files=os.listdir('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/7')
for filename in files:
    im=cv2.imread('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/7/'+filename)
    im2=cv2.resize(im,(8,32))
    im3=cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4=im3.flatten()
    x=np.append(x,[im4],axis=0)
    y=np.append(y,7)

In [89]:
files=os.listdir('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/8')
for filename in files:
    im=cv2.imread('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/8/'+filename)
    im2=cv2.resize(im,(8,32))
    im3=cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4=im3.flatten()
    x=np.append(x,[im4],axis=0)
    y=np.append(y,8)

In [92]:
files=os.listdir('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/9')
for filename in files:
    im=cv2.imread('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/9/'+filename)
    im2=cv2.resize(im,(8,32))
    im3=cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4=im3.flatten()
    x=np.append(x,[im4],axis=0)
    y=np.append(y,9)

In [93]:
x.shape

(3429, 256)

In [94]:
y[3400]

9.0

In [95]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [96]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [97]:
model=linear_model.LogisticRegression()

In [98]:
model.fit(X_train,y_train)

C:\Users\User\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [99]:
out=model.predict(X_test)

In [100]:
out

array([7., 4., 4., 6., 4., 5., 8., 5., 9., 8., 8., 5., 4., 4., 7., 9., 4.,
       4., 8., 3., 3., 3., 4., 4., 7., 4., 4., 8., 4., 5., 9., 1., 7., 9.,
       3., 5., 9., 2., 4., 5., 4., 9., 1., 7., 5., 5., 2., 1., 1., 5., 8.,
       9., 7., 1., 9., 2., 7., 4., 8., 7., 7., 5., 1., 2., 4., 9., 2., 4.,
       3., 2., 1., 4., 4., 2., 4., 7., 2., 3., 5., 1., 2., 1., 5., 3., 8.,
       1., 3., 2., 1., 7., 9., 5., 9., 2., 5., 7., 5., 7., 5., 7., 4., 4.,
       6., 9., 8., 7., 4., 7., 3., 3., 4., 6., 9., 1., 4., 2., 8., 4., 8.,
       9., 2., 9., 4., 1., 4., 8., 9., 1., 6., 4., 7., 8., 3., 4., 6., 6.,
       5., 4., 9., 5., 2., 1., 4., 1., 5., 8., 2., 2., 9., 4., 9., 3., 1.,
       3., 4., 4., 2., 7., 7., 7., 8., 8., 1., 1., 5., 5., 8., 8., 6., 6.,
       5., 6., 5., 3., 2., 4., 1., 8., 8., 6., 1., 2., 8., 4., 9., 4., 5.,
       5., 4., 1., 5., 8., 4., 1., 4., 6., 4., 8., 4., 8., 9., 5., 3., 4.,
       3., 2., 2., 8., 4., 9., 4., 4., 8., 4., 9., 5., 1., 4., 9., 1., 5.,
       7., 4., 1., 2., 3.

In [101]:
y_test

array([7., 4., 4., 6., 4., 5., 8., 5., 9., 8., 8., 5., 4., 4., 8., 9., 4.,
       4., 8., 3., 3., 3., 4., 3., 7., 4., 4., 8., 4., 5., 9., 1., 8., 9.,
       3., 5., 9., 2., 4., 2., 4., 9., 1., 7., 5., 7., 2., 1., 1., 5., 8.,
       9., 7., 1., 9., 2., 7., 4., 8., 7., 7., 2., 1., 2., 4., 9., 2., 4.,
       3., 2., 1., 4., 2., 2., 4., 7., 2., 6., 5., 1., 2., 1., 5., 3., 8.,
       1., 3., 2., 3., 7., 9., 1., 9., 2., 5., 7., 5., 7., 5., 7., 4., 4.,
       6., 9., 8., 7., 4., 7., 3., 3., 4., 6., 9., 1., 6., 2., 8., 4., 8.,
       9., 2., 9., 6., 1., 4., 8., 9., 1., 6., 4., 7., 8., 3., 4., 6., 6.,
       5., 4., 9., 5., 2., 1., 4., 1., 5., 8., 2., 2., 9., 4., 9., 3., 1.,
       3., 4., 4., 2., 7., 6., 7., 8., 8., 7., 1., 5., 5., 8., 8., 6., 6.,
       5., 6., 5., 1., 2., 4., 1., 8., 8., 6., 9., 2., 8., 4., 9., 4., 5.,
       5., 4., 1., 5., 8., 4., 1., 4., 6., 4., 8., 4., 5., 9., 5., 8., 4.,
       3., 2., 2., 8., 4., 9., 4., 4., 8., 4., 9., 5., 1., 4., 9., 1., 5.,
       7., 4., 1., 2., 3.

In [102]:
x1=np.empty((0,256))
im=cv2.imread('D:/AIO.learn/10-ML-Projects/pelak_detect/pelak/1/1 (154).jpg')
im2=cv2.resize(im,(8,32))
im3=cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
im4=im3.flatten()
x1=np.append(x1,[im4],axis=0)

In [103]:
natije=model.predict(x1)

In [104]:
natije

array([1.])